const STORAGE_KEY = 'foodbridge-listings-v1';
const now = Date.now();
let listings = [], currentType = 'all', map, markersLayer, userMarker, userLocation = null, mapReady = false;

const seedListings = [
  {id:'d1',type:'donation',providerName:'GreenLeaf Hostel Mess',providerType:'Hostel',foodName:'Rice, Dal & Vegetables',description:'Freshly prepared vegetarian lunch, packed for collection.',foodCategory:'Prepared meals',vegetarian:true,quantity:42,meals:42,address:'Lovely Professional University, Phagwara',latitude:31.255,longitude:75.705,createdAt:now-22*60000,pickupDeadline:now+88*60000,claimDeadline:now+88*60000,status:'active',collectionInstructions:'Collect from the mess entrance. Please bring insulated containers.',claimedBy:null},
  {id:'d2',type:'donation',providerName:'Campus Corner Restaurant',providerType:'Restaurant',foodName:'Veg Biryani + Raita',description:'Sealed portions from today’s lunch service.',foodCategory:'Prepared meals',vegetarian:true,quantity:28,meals:28,address:'Jalandhar–Phagwara Highway',latitude:31.261,longitude:75.699,createdAt:now-36*60000,pickupDeadline:now+42*60000,claimDeadline:now+42*60000,status:'active',collectionInstructions:'Ask for the manager at the front desk.',claimedBy:null},
  {id:'d3',type:'donation',providerName:'Helping Hands Household',providerType:'Household',foodName:'Fresh Home-Cooked Meals',description:'Wholesome vegetarian meals, safely packed.',foodCategory:'Prepared meals',vegetarian:true,quantity:8,meals:8,address:'Model Town, Phagwara',latitude:31.227,longitude:75.773,createdAt:now-14*60000,pickupDeadline:now+118*60000,claimDeadline:now+118*60000,status:'active',collectionInstructions:'Please call when you reach the building.',claimedBy:null},
  {id:'s1',type:'sell',providerName:'Sunrise Café',providerType:'Café',foodName:'Fresh Veg Sandwich Box',description:'Four freshly made sandwich portions, ready for quick pickup.',foodCategory:'Snacks',vegetarian:true,quantity:6,availableQuantity:6,address:'LPU Main Gate, Phagwara',latitude:31.253,longitude:75.704,createdAt:now-28*60000,pickupDeadline:now+74*60000,reservationDeadline:now+74*60000,status:'active',originalPrice:250,discountedPrice:90,discountPercentage:64,reservedQuantity:0},
  {id:'s2',type:'sell',providerName:'Sweet Crumbs Bakery',providerType:'Bakery',foodName:'Assorted Pastry Box',description:'A mixed box of freshly baked pastries.',foodCategory:'Bakery & desserts',vegetarian:true,quantity:4,availableQuantity:4,address:'GT Road, Phagwara',latitude:31.257,longitude:75.710,createdAt:now-46*60000,pickupDeadline:now+54*60000,reservationDeadline:now+54*60000,status:'active',originalPrice:400,discountedPrice:160,discountPercentage:60,reservedQuantity:0},
  {id:'s3',type:'sell',providerName:'Pizza Corner',providerType:'Restaurant',foodName:'Fresh Meal Combo',description:'A meal combo from today’s kitchen run.',foodCategory:'Prepared meals',vegetarian:false,quantity:3,availableQuantity:3,address:'Law Gate, Phagwara',latitude:31.252,longitude:75.698,createdAt:now-9*60000,pickupDeadline:now+155*60000,reservationDeadline:now+155*60000,status:'active',originalPrice:500,discountedPrice:220,discountPercentage:56,reservedQuantity:0}
];

function loadListings(){ try { listings = JSON.parse(localStorage.getItem(STORAGE_KEY)) || seedListings; } catch { listings = seedListings; } updateExpiries(); }
function saveListingsToLocalStorage(){localStorage.setItem(STORAGE_KEY,JSON.stringify(listings));}
function getActiveListings(){return listings.filter(l=>l.status==='active' && deadline(l)>Date.now())}
function getDonationListings(){return getActiveListings().filter(l=>l.type==='donation')}
function getSellListings(){return getActiveListings().filter(l=>l.type==='sell')}
function getListingById(id){return listings.find(l=>l.id===id)}
function addListing(listing){listings.unshift(listing);saveListingsToLocalStorage()}
function updateListing(id,changes){const l=getListingById(id);if(l){Object.assign(l,changes);saveListingsToLocalStorage()}}
function removeListing(id){listings=listings.filter(l=>l.id!==id);saveListingsToLocalStorage()}
function deadline(l){return l.type==='donation'?l.claimDeadline:l.reservationDeadline}
function updateExpiries(){let changed=false;listings.forEach(l=>{if(l.status==='active'&&deadline(l)<=Date.now()){l.status='expired';changed=true}});if(changed)saveListingsToLocalStorage()}
function distanceKm(lat1,lon1,lat2,lon2){const R=6371,dLat=(lat2-lat1)*Math.PI/180,dLon=(lon2-lon1)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function distanceText(l){if(!userLocation)return 'Nearby';return `${distanceKm(userLocation.lat,userLocation.lng,l.latitude,l.longitude).toFixed(1)} km away`}
function timeText(ms){if(ms<=0)return 'Expired';const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function urgency(l){const ms=deadline(l)-Date.now();return ms<3600000?'urgent':'available'}
function emoji(l){if(l.foodCategory==='Bakery & desserts')return '🧁';if(l.foodCategory==='Snacks')return '🥪';return l.type==='donation'?'🍛':'🍱'}

function listingCard(l){const isD=l.type==='donation', urgencyClass=urgency(l), statusText=isD?(urgencyClass==='urgent'?'⚡ CLAIM SOON':'♥ DONATION'):`${l.discountPercentage}% OFF`;const qty=isD?`${l.meals} meals`:`${l.availableQuantity} available`;return `<article class="food-card ${isD?'donation':'sell'}"><div class="card-image">${emoji(l)}<span class="tag ${isD?'donate':'sell'}">${statusText}</span></div><div class="food-info"><div class="food-meta"><span>${qty}</span><span>⌖ ${distanceText(l)}</span></div><h3>${l.foodName}</h3><small>${l.providerName}</small>${isD?'':`<div class="price"><s>₹${l.originalPrice}</s><b>₹${l.discountedPrice}</b> <small>You save ₹${l.originalPrice-l.discountedPrice}</small></div>`}<div class="card-bottom"><span class="countdown ${urgencyClass}">${isD?'Claim':'Pickup'} in ${timeText(deadline(l)-Date.now())}</span><button class="claim-btn" onclick="openAction('${l.id}')">${isD?'CLAIM FOOD →':'RESERVE NOW →'}</button></div></div></article>`}
function filteredListings(){let arr=getActiveListings();const search=(document.getElementById('searchInput')?.value||'').toLowerCase();const veg=document.getElementById('vegOnly')?.checked;const radius=+(document.getElementById('radiusSelect')?.value||0);if(currentType!=='all')arr=arr.filter(l=>l.type===currentType);if(search)arr=arr.filter(l=>`${l.foodName} ${l.providerName} ${l.address}`.toLowerCase().includes(search));if(veg)arr=arr.filter(l=>l.vegetarian);if(radius&&userLocation)arr=arr.filter(l=>distanceKm(userLocation.lat,userLocation.lng,l.latitude,l.longitude)<=radius);const sort=document.getElementById('sortSelect')?.value||'recent';if(sort==='near'&&userLocation)arr.sort((a,b)=>distanceKm(userLocation.lat,userLocation.lng,a.latitude,a.longitude)-distanceKm(userLocation.lat,userLocation.lng,b.latitude,b.longitude));if(sort==='urgent')arr.sort((a,b)=>deadline(a)-deadline(b));if(sort==='discount')arr.sort((a,b)=>(b.discountPercentage||0)-(a.discountPercentage||0));return arr}
function renderListings(){updateExpiries();const arr=filteredListings(),out=arr.map(listingCard).join('')||'<p class="empty">No active listings match those filters. Try another search, or be the first to post one.</p>';const target=document.getElementById('listingResults');if(target)target.innerHTML=out;const sell=document.getElementById('sellResults');if(sell)sell.innerHTML=getSellListings().map(listingCard).join('')||'<p class="empty">No deals live right now.</p>';const donations=document.getElementById('donationResults');if(donations)donations.innerHTML=getDonationListings().map(listingCard).join('')||'<p class="empty">No donation listings live right now.</p>';if(mapReady)renderMapMarkers(arr);const mapCount=document.getElementById('mapCount');if(mapCount)mapCount.textContent=`${arr.length} live listing${arr.length===1?'':'s'}`;document.getElementById('topMeals').textContent=(1284+listings.filter(l=>l.status==='claimed'||l.status==='reserved').reduce((n,l)=>n+(l.meals||1),0)).toLocaleString()}

function setType(type){currentType=type;document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('selected',b.dataset.type===type));renderListings()}
function setLayout(layout){const node=document.getElementById('listingLayout');node.classList.toggle('map-mode',layout==='map');document.getElementById('listBtn').classList.toggle('selected',layout==='list');document.getElementById('mapBtn').classList.toggle('selected',layout==='map');if(layout==='map'){setTimeout(initMap,50)} }
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('#mainNav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`));document.getElementById('mainNav').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});renderListings();if(id==='impact')animateCounters();}
function initMap(){if(!mapReady){map=L.map('map',{zoomControl:true}).setView([31.254,75.704],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);markersLayer=L.layerGroup().addTo(map);mapReady=true;}map.invalidateSize();renderMapMarkers(filteredListings())}
function renderMapMarkers(arr){if(!mapReady)return;markersLayer.clearLayers();arr.forEach(l=>{const icon=L.divIcon({className:'map-marker',html:`<div class="pin ${l.type==='sell'?'sell':''}"><span>${l.type==='sell'?'₹':'♥'}</span></div>`,iconSize:[31,31],iconAnchor:[15,31]});const action=l.type==='donation'?'CLAIM FOOD':'VIEW DEAL';L.marker([l.latitude,l.longitude],{icon}).bindPopup(`<div class="map-popup"><span class="tag ${l.type==='donation'?'donate':'sell'}">${l.type==='donation'?(urgency(l)==='urgent'?'URGENT':'DONATION'):`${l.discountPercentage}% OFF`}</span><b>${l.foodName}</b><small>${l.providerName}</small><br><small>${l.type==='donation'?l.meals+' meals':`₹${l.discountedPrice} · ${l.availableQuantity} left`} · ${distanceText(l)}</small><br><small>${l.type==='donation'?'Claim':'Pickup'} in ${timeText(deadline(l)-Date.now())}</small><button onclick="openAction('${l.id}')">${action}</button><button class="directions" onclick="openDirections('${l.id}')">OPEN DIRECTIONS ↗</button></div>`).addTo(markersLayer)});if(userMarker)userMarker.addTo(map)}
function openDirections(id){const l=getListingById(id);if(!l)return;const start=userLocation?`${userLocation.lat},${userLocation.lng}/`:'';window.open(`https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=${start}${l.latitude},${l.longitude}`,'_blank','noopener')}
function useLocation(){const status=document.getElementById('locationStatus');if(!navigator.geolocation){status.textContent='Your browser does not support location. You can still search manually.';return}status.textContent='Requesting your location…';navigator.geolocation.getCurrentPosition(pos=>{userLocation={lat:pos.coords.latitude,lng:pos.coords.longitude};status.textContent='Location set. Listings are now sorted by distance when you choose “Nearest first”.';initMap();if(userMarker)map.removeLayer(userMarker);userMarker=L.marker([userLocation.lat,userLocation.lng]).bindPopup('You are here').addTo(map);map.setView([userLocation.lat,userLocation.lng],14);renderListings()},()=>{status.textContent='Location access helps us show food near you. You can still browse listings or search for a location manually.'},{enableHighAccuracy:true,timeout:10000})}
async function manualSearch(){const place=prompt('Enter a city, locality or address');if(!place)return;const status=document.getElementById('locationStatus');status.textContent='Finding that location…';try{const res=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(place)}`);const data=await res.json();if(!data.length)throw new Error();userLocation={lat:+data[0].lat,lng:+data[0].lon};status.textContent=`Showing food around ${data[0].display_name.split(',').slice(0,2).join(',')}.`;initMap();map.setView([userLocation.lat,userLocation.lng],13);renderListings()}catch{status.textContent='We couldn’t find that place. Try a city or neighbourhood name.'}}
function openAction(id){const l=getListingById(id);if(!l||l.status!=='active'){showToast('This listing is no longer available.');return}const isD=l.type==='donation';document.getElementById('modalContent').innerHTML=`<p class="eyebrow">${isD?'CONFIRM COLLECTION':'CONFIRM RESERVATION'}</p><h2>${isD?'Claim this food?':'Reserve this deal?'}</h2><div class="modal-detail"><b>${l.foodName}</b>${l.providerName}<br>${isD?`${l.meals} meals`:`₹${l.discountedPrice} · ${l.availableQuantity} available`} · ${distanceText(l)}<br><small>${l.address}</small></div><p>${isD?'By claiming, you’re confirming you can collect before the safe pickup window closes.':'Reserve now, then collect directly from the provider before the pickup window closes.'}</p><div class="modal-actions"><button class="button ghost" onclick="closeModal()">Not now</button><button class="button" onclick="confirmAction('${l.id}')">${isD?'Claim food':'Reserve deal'} →</button></div>`;document.getElementById('modal').classList.add('open')}
function confirmAction(id){const l=getListingById(id),isD=l.type==='donation';if(isD)updateListing(id,{status:'claimed',claimedBy:'You',claimedAt:Date.now()});else updateListing(id,{status:'reserved',reservedQuantity:(l.reservedQuantity||0)+1,availableQuantity:l.availableQuantity-1});closeModal();showToast(isD?'Food claimed — collection details are saved.':'Deal reserved — enjoy your pickup!');renderListings()}
function closeModal(){document.getElementById('modal').classList.remove('open')}
function choosePostType(type){document.getElementById('listingType').value=type;document.querySelectorAll('.post-type').forEach(b=>b.classList.toggle('active',b.dataset.posttype===type));togglePostFields()}
function togglePostFields(){document.getElementById('saleFields').classList.toggle('hidden',document.getElementById('listingType').value!=='sell')}
function handlePost(e){e.preventDefault();const type=document.getElementById('listingType').value,mins=+document.getElementById('minutes').value,op=+document.getElementById('originalPrice').value,dp=+document.getElementById('discountedPrice').value;if(type==='sell'&&(!op||!dp||dp>=op)){showToast('Please enter a discounted price lower than the original price.');return}const l={id:'custom-'+Date.now(),type,providerName:document.getElementById('providerName').value,providerType:'Community provider',foodName:document.getElementById('foodName').value,description:document.getElementById('notes').value,foodCategory:document.getElementById('category').value,vegetarian:document.getElementById('vegetarian').checked,quantity:+document.getElementById('quantity').value,meals:+document.getElementById('quantity').value,availableQuantity:+document.getElementById('quantity').value,address:document.getElementById('address').value,latitude:31.254+(Math.random()-.5)*.025,longitude:75.704+(Math.random()-.5)*.025,createdAt:Date.now(),pickupDeadline:Date.now()+mins*60000,claimDeadline:Date.now()+mins*60000,reservationDeadline:Date.now()+mins*60000,status:'active',collectionInstructions:document.getElementById('notes').value,claimedBy:null,originalPrice:op,discountedPrice:dp,discountPercentage:type==='sell'?Math.round((1-dp/op)*100):0,reservedQuantity:0};addListing(l);e.target.reset();choosePostType('donation');showView(type==='sell'?'sell':'donate');showToast('Your listing is now live for nearby people.');}
function showToast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3600)}
function animateCounters(){document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count,start=performance.now(),duration=900;function tick(t){const p=Math.min((t-start)/duration,1);el.textContent=Math.round(target*(1-(1-p)**3)).toLocaleString();if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}
document.getElementById('postForm').addEventListener('submit',handlePost);document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
function routeFromHash(){const route=location.hash.slice(1);const valid=['home','find','sell','donate','post','impact','login'];showView(valid.includes(route)?route:'home')}
window.addEventListener('hashchange',routeFromHash);
function updateImpact(){const claimed=listings.filter(l=>l.status==='claimed'),reserved=listings.filter(l=>l.status==='reserved'),rescued=claimed.reduce((n,l)=>n+(l.meals||l.quantity||0),0)+reserved.reduce((n,l)=>n+(l.reservedQuantity||1),0),active=getActiveListings().length,totalMeals=18420+rescued,totalFood=7000+rescued*.38,totalPeople=13200+Math.round(rescued*.72);const set=(id,value)=>{const node=document.getElementById(id);if(node)node.textContent=value};set('impactMeals',totalMeals.toLocaleString());set('impactWaste',`${totalFood.toFixed(0)} kg`);set('impactPeople',totalPeople.toLocaleString());set('monthlyMeals',Math.round(totalMeals/12).toLocaleString());set('monthlyFood',`${Math.round(totalFood/12)} kg`);set('monthlyPeople',Math.round(totalPeople/12).toLocaleString());set('liveAvailable',active);set('liveClaims',claimed.length);set('liveReservations',reserved.length);const summary=document.getElementById('impactSummary');if(summary)summary.textContent=rescued?`${rescued} meals and food portions have been rescued through actions in this browser. Your activity is now included in FoodBridge’s collective impact.`:`${active} time-sensitive listings are waiting for a nearby person or organisation to act. Your next claim can become part of FoodBridge’s collective impact.`}
function switchAuth(mode){document.getElementById('loginForm').classList.toggle('hidden',mode==='signup');document.getElementById('signupForm').classList.toggle('hidden',mode!=='signup')}
function setDemoUser(name,email){localStorage.setItem('foodbridge-demo-user',JSON.stringify({name,email}));const login=document.getElementById('loginButton');if(login){login.textContent=`Hi, ${name.split(' ')[0]}`;login.onclick=()=>{showView('impact')}}}
function handleLogin(event){event.preventDefault();const email=document.getElementById('loginEmail').value;setDemoUser(email.split('@')[0],email);showView('impact');showToast('You’re logged in to the FoodBridge demo.')}
function handleSignup(event){event.preventDefault();const name=document.getElementById('signupName').value.trim();const email=document.getElementById('signupEmail').value;setDemoUser(name,email);showView('impact');showToast(`Welcome to FoodBridge, ${name}!`)}
loadListings();const savedUser=JSON.parse(localStorage.getItem('foodbridge-demo-user')||'null');if(savedUser)setDemoUser(savedUser.name,savedUser.email);document.getElementById('loginForm').addEventListener('submit',handleLogin);document.getElementById('signupForm').addEventListener('submit',handleSignup);routeFromHash();updateImpact();setInterval(()=>{renderListings();updateImpact()},1000);
